version: "2"
services:
  jenkins:
    build: .
    expose:
      - 8080
    ports:
      - 50000:50000
    networks:
      - default
      - reverse-proxy
    restart: always
    volumes:
      - ./jenkins_home:/var/jenkins_home
    environment:
      - VIRTUAL_PORT=8080
      - VIRTUAL_HOST=jenkins.nguyenantoine.com
      - LETSENCRYPT_HOST=jenkins.nguyenantoine.com
      - LETSENCRYPT_EMAIL=antoine.ngu@outlook.fr
networks:
  reverse-proxy:
    external:
      name: reverse-proxy

