version: "2"
services:
  jenkins:
    build: .
    expose:
      - 8080
    ports:
      - 50000:50000
    networks:
      - default
      - reverse-proxy
    volumes:
      - ./jenkins_home:/var/jenkins_home
    env_file:
      - .env
    restart: always
networks:
  reverse-proxy:
    external:
      name: reverse-proxy

